import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, extname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = resolve(join(dirname(fileURLToPath(import.meta.url)), '..'));
const AUTO_MARKER = '<!-- auto-generated by skillgraph -->';

export const PROVIDER_PRESETS = [
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    popularityRank: 1,
    popularityBasis: 'Largest public user signal among covered tools.',
    roots: [
      '.github/copilot-instructions.md',
      '.github/instructions',
      '.github/prompts',
      '.github/agents',
      '.github/chatmodes',
      'AGENTS.md',
    ],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    popularityRank: 2,
    popularityBasis: 'Large AI editor adoption and native project rules.',
    roots: ['.cursor/rules', '.cursorrules', 'AGENTS.md'],
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    popularityRank: 3,
    popularityBasis: 'Major agentic coding tool with project memory, skills, commands, and subagents.',
    roots: ['CLAUDE.md', '.claude/CLAUDE.md', '.claude/skills', '.claude/commands', '.claude/agents', '.claude/rules'],
  },
  {
    id: 'openai-codex',
    name: 'OpenAI Codex',
    popularityRank: 4,
    popularityBasis: 'Native AGENTS.md workflow and strong public open-source repository signal.',
    roots: ['AGENTS.md', 'AGENTS.override.md'],
  },
  {
    id: 'cline',
    name: 'Cline',
    popularityRank: 5,
    popularityBasis: 'Popular open-source VS Code autonomous coding agent.',
    roots: ['.clinerules', '.cursorrules', '.windsurfrules', 'AGENTS.md', 'memory-bank'],
  },
  {
    id: 'kilo-code',
    name: 'Kilo Code',
    popularityRank: 6,
    popularityBasis: 'Popular open-source VS Code agent with project rules and JSONC instructions.',
    roots: ['kilo.jsonc', 'kilo.json', '.kilo/rules', '.kilocode/rules', '.kilocode/rules-code', '.kilocoderules', 'AGENTS.md'],
  },
  {
    id: 'agent-skills',
    name: 'Generic Agent Skills',
    popularityRank: 7,
    popularityBasis: 'Tool-agnostic skill roots used by multi-agent teams.',
    roots: ['.agents/skills'],
  },
];

const DEFAULT_CONFIG = {
  providers: PROVIDER_PRESETS.map((provider) => provider.id),
  roots: [],
  outDir: 'docs/skills',
  canonicalRoots: ['.agents/skills'],
  wrapperRoots: ['.claude/skills'],
  exclude: ['**/node_modules/**', '**/.git/**'],
  instructionExtensions: ['.md', '.mdc', '.txt', '.json', '.jsonc', '.yaml', '.yml'],
  helperPatterns: [
    'scripts/**/*.mjs',
    'scripts/**/*.js',
    'scripts/**/*.cjs',
    'scripts/**/*.sh',
    'bin/**/*.mjs',
  ],
  privacy: {
    includeEvidence: true,
    redactTerms: [],
  },
  rules: {
    stalePatterns: [],
  },
};

function normalizePath(path) {
  return path.split(/[\\/]+/).join('/');
}

function slug(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'node';
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function jsonStable(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function contentHash(value) {
  return createHash('sha256').update(jsonStable(value)).digest('hex').slice(0, 12);
}

function deepMerge(base, override) {
  if (!override || typeof override !== 'object') return base;
  const output = { ...base };
  for (const [key, value] of Object.entries(override)) {
    if (Array.isArray(value)) output[key] = value;
    else if (value && typeof value === 'object' && !Array.isArray(value)) {
      output[key] = deepMerge(base[key] || {}, value);
    } else output[key] = value;
  }
  return output;
}

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function unique(values) {
  return [...new Set(values.filter(Boolean).map(normalizePath))];
}

function selectedProviders(config) {
  const selected = new Set(config.providers || []);
  return PROVIDER_PRESETS
    .filter((provider) => selected.has(provider.id))
    .sort((a, b) => a.popularityRank - b.popularityRank);
}

function expandProviderRoots(config) {
  return unique([
    ...selectedProviders(config).flatMap((provider) => provider.roots),
    ...(config.roots || []),
  ]);
}

function providersForRoot(rootRel, config) {
  const root = normalizePath(rootRel);
  return selectedProviders(config).filter((provider) => provider.roots.map(normalizePath).includes(root));
}

export function loadConfig(options = {}) {
  const rootDir = resolve(options.rootDir || process.cwd());
  const configPath = options.configPath
    ? resolve(rootDir, options.configPath)
    : resolve(rootDir, 'skillgraph.config.json');
  const config = existsSync(configPath)
    ? deepMerge(DEFAULT_CONFIG, readJson(configPath))
    : { ...DEFAULT_CONFIG };
  if (options.outDir) config.outDir = options.outDir;
  if (options.roots?.length) config.roots = options.roots;
  config.roots = expandProviderRoots(config);
  return {
    ...config,
    rootDir,
    outDirAbs: resolve(rootDir, config.outDir),
    configPath: existsSync(configPath) ? configPath : null,
  };
}

export function parseFrontmatter(text) {
  if (!text.startsWith('---\n')) return {};
  const end = text.indexOf('\n---', 4);
  if (end === -1) return {};
  const raw = text.slice(4, end).trim();
  const frontmatter = {};
  for (const line of raw.split('\n')) {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) continue;
    let value = match[2].trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    frontmatter[match[1]] = value;
  }
  return frontmatter;
}

function globToRegExp(pattern) {
  const input = normalizePath(pattern);
  let output = '';
  for (let index = 0; index < input.length; index += 1) {
    const char = input[index];
    const next = input[index + 1];
    if (char === '*' && next === '*') {
      output += '.*';
      index += 1;
    } else if (char === '*') {
      output += '[^/]*';
    } else if ('\\.+?^${}()|[]'.includes(char)) {
      output += `\\${char}`;
    } else {
      output += char;
    }
  }
  return new RegExp(`^${output}$`);
}

function isExcluded(repoPath, excludePatterns) {
  return excludePatterns.some((pattern) => globToRegExp(pattern).test(repoPath));
}

function isInstructionFile(filePath, config) {
  return config.instructionExtensions.includes(extname(filePath).toLowerCase());
}

function walkInstructionFiles(rootAbs, rootDir, config, currentAbs = rootAbs, result = []) {
  if (!existsSync(currentAbs)) return result;
  const stat = statSync(currentAbs);
  if (stat.isFile()) {
    result.push(currentAbs);
    return result;
  }
  for (const entry of readdirSync(currentAbs)) {
    const fullPath = join(currentAbs, entry);
    const repoPath = normalizePath(relative(rootDir, fullPath));
    if (isExcluded(repoPath, config.exclude)) continue;
    const entryStat = statSync(fullPath);
    if (entryStat.isDirectory()) {
      walkInstructionFiles(rootAbs, rootDir, config, fullPath, result);
    } else if (isInstructionFile(entry, config)) {
      result.push(fullPath);
    }
  }
  return result;
}

function inferNameFromPath(relativePath, frontmatter) {
  if (frontmatter.name) return frontmatter.name;
  const normalized = normalizePath(relativePath);
  const parts = normalized.split('/');
  if (basename(normalized) === 'SKILL.md' && parts.length >= 2) {
    return parts[parts.length - 2];
  }
  return basename(normalized, extname(normalized));
}

function classifyNode(rootRel, relativePath, frontmatter, text, config) {
  const normalizedRoot = normalizePath(rootRel);
  const normalizedPath = normalizePath(relativePath);
  const canonicalRoots = config.canonicalRoots.map(normalizePath);
  const wrapperRoots = config.wrapperRoots.map(normalizePath);
  if (canonicalRoots.includes(normalizedRoot) && basename(normalizedPath) === 'SKILL.md') {
    return 'canonical-skill';
  }
  const mentionsCanonicalRoot = canonicalRoots.some((root) => text.includes(`${root}/`));
  if (
    wrapperRoots.includes(normalizedRoot) &&
    (text.includes('Canonical skill instructions live at:') || mentionsCanonicalRoot)
  ) {
    return 'wrapper';
  }
  if (basename(normalizedPath) === 'SKILL.md' || frontmatter.name) {
    return 'skill';
  }
  return 'skill-doc';
}

function firstMeaningfulLine(text) {
  return text
    .split('\n')
    .map((line) => line.trim())
    .find((line) => line && !line.startsWith('---') && !line.startsWith('<!--') && !line.startsWith('#'));
}

function redact(value, terms = []) {
  let output = String(value ?? '');
  for (const term of terms.filter(Boolean)) {
    output = output.replaceAll(term, '[redacted]');
  }
  return output;
}

function extractDescription(text, frontmatter, config) {
  const description = frontmatter.description || firstMeaningfulLine(text) || '';
  return redact(description.slice(0, 220), config.privacy.redactTerms);
}

function collectSkillNodes(config) {
  const nodes = [];
  for (const rootRel of config.roots) {
    const rootAbs = resolve(config.rootDir, rootRel);
    const rootIsFile = existsSync(rootAbs) && statSync(rootAbs).isFile();
    for (const fullPath of walkInstructionFiles(rootAbs, config.rootDir, config)) {
      const relativeToRoot = rootIsFile
        ? basename(fullPath)
        : normalizePath(relative(rootAbs, fullPath));
      const repoPath = normalizePath(relative(config.rootDir, fullPath));
      const text = readFileSync(fullPath, 'utf8');
      const frontmatter = parseFrontmatter(text);
      const name = inferNameFromPath(relativeToRoot, frontmatter);
      const kind = classifyNode(rootRel, relativeToRoot, frontmatter, text, config);
      const providers = providersForRoot(rootRel, config);
      const providerNames = providers.length ? providers.map((provider) => provider.name) : ['Custom'];
      const id = rootIsFile ? `file:${repoPath}` : `${normalizePath(rootRel)}:${relativeToRoot}`;
      nodes.push({
        id,
        name: redact(name, config.privacy.redactTerms),
        rawName: name,
        normalizedName: slug(name),
        label: redact(name, config.privacy.redactTerms),
        kind,
        providers: providers.length ? providers.map((provider) => provider.id) : ['custom'],
        provider: providers[0]?.id || 'custom',
        providerNames,
        providerName: providerNames.join(' / '),
        popularityRank: providers[0]?.popularityRank || 999,
        root: normalizePath(rootRel),
        path: repoPath,
        description: extractDescription(text, frontmatter, config),
        bytes: Buffer.byteLength(text, 'utf8'),
        tokenEstimate: Math.ceil(Buffer.byteLength(text, 'utf8') / 4),
        frontmatter: Object.fromEntries(
          Object.entries(frontmatter).map(([key, value]) => [key, redact(value, config.privacy.redactTerms)]),
        ),
        text,
      });
    }
  }
  return nodes.sort((a, b) => a.path.localeCompare(b.path));
}

function addEdge(edges, source, target, type, evidence = '', config = DEFAULT_CONFIG) {
  if (!source || !target || source === target) return;
  const key = `${source}->${target}:${type}`;
  if (edges.some((edge) => edge.key === key)) return;
  edges.push({
    key,
    id: `edge-${edges.length + 1}`,
    source,
    target,
    type,
    label: type.replaceAll('-', ' '),
    evidence: config.privacy.includeEvidence
      ? redact(evidence.replace(/\s+/g, ' ').trim().slice(0, 220), config.privacy.redactTerms)
      : '',
  });
}

function evidenceNear(text, needle) {
  const index = text.toLowerCase().indexOf(String(needle).toLowerCase());
  if (index === -1) return '';
  return text.slice(Math.max(0, index - 90), Math.min(text.length, index + String(needle).length + 90));
}

function referenceTypeForEvidence(evidence) {
  if (/(before returning|route through|orchestrates|delegate|depends|invoke|run|use|calls)/i.test(evidence)) {
    return 'calls';
  }
  return 'references';
}

function createScriptNode(scriptPath, config, nodes) {
  const normalized = normalizePath(scriptPath).replace(/[.,;:]+$/g, '');
  const existing = nodes.find((node) => node.id === `script:${normalized}`);
  if (existing) return existing.id;
  const abs = resolve(config.rootDir, normalized);
  const bytes = existsSync(abs) ? Buffer.byteLength(readFileSync(abs, 'utf8'), 'utf8') : 0;
  nodes.push({
    id: `script:${normalized}`,
    name: basename(normalized),
    rawName: basename(normalized),
    normalizedName: slug(basename(normalized)),
    label: basename(normalized),
    kind: existsSync(abs) ? 'helper-script' : 'missing-helper',
    providers: ['helper'],
    provider: 'helper',
    providerNames: ['Helper Script'],
    providerName: 'Helper Script',
    popularityRank: 999,
    root: dirname(normalized),
    path: normalized,
    description: existsSync(abs) ? 'Helper script referenced by a skill.' : 'Referenced helper script was not found.',
    bytes,
    tokenEstimate: Math.ceil(bytes / 4),
    frontmatter: {},
  });
  return `script:${normalized}`;
}

function resolveHelperReference(candidate, sourceNode, config, sourceText = '') {
  const normalized = normalizePath(candidate).replace(/[.,;:]+$/g, '');
  if (!normalized.startsWith('scripts/')) return normalized;
  const matchingLines = sourceText
    .split('\n')
    .filter((line) => line.includes(candidate) || line.includes(normalized));
  for (const line of matchingLines) {
    const cdMatch = line.match(/\bcd\s+(["']?)([^"';&|`\s]+)\1/);
    if (!cdMatch) continue;
    const cwd = normalizePath(cdMatch[2]).replace(/^\.\//, '').replace(/^\.\.\//, '');
    const cwdCandidate = normalizePath(join(cwd, normalized));
    if (existsSync(resolve(config.rootDir, cwdCandidate))) return cwdCandidate;
  }
  if (existsSync(resolve(config.rootDir, normalized))) return normalized;
  const sourceRelative = normalizePath(join(dirname(sourceNode.path), normalized));
  if (existsSync(resolve(config.rootDir, sourceRelative))) return sourceRelative;
  return normalized;
}

function helperRegexes(config) {
  const roots = [...new Set([...config.roots, ...config.canonicalRoots, ...config.wrapperRoots])].map(normalizePath);
  const rootPattern = roots.map(escapeRegExp).join('|');
  return [
    new RegExp(`((${rootPattern})/[^\\s\`'")]+/scripts/[^\\s\`'")]+)`, 'g'),
    /(?:^|[\s`'"])((?:[A-Za-z0-9_.-]+\/)+scripts\/[A-Za-z0-9_./-]+\.(?:mjs|cjs|js|sh|ts))/g,
    /(?:^|[\s`'"])((?:scripts|bin)\/[A-Za-z0-9_./-]+\.(?:mjs|cjs|js|sh|ts))/g,
  ];
}

function inferEdges(config, nodes) {
  const edges = [];
  const skillNodes = nodes.filter((node) => node.text);
  const canonicalByName = new Map();
  for (const node of skillNodes) {
    if (node.kind === 'canonical-skill' && !canonicalByName.has(node.normalizedName)) {
      canonicalByName.set(node.normalizedName, node);
    }
  }

  const canonicalRootPattern = config.canonicalRoots.map(escapeRegExp).join('|');
  const canonicalRefRegex = new RegExp(`(?:${canonicalRootPattern})/([^/\\s\`'")]+)/SKILL\\.md`, 'g');

  for (const node of skillNodes) {
    const text = node.text;
    for (const match of text.matchAll(canonicalRefRegex)) {
      const target = canonicalByName.get(slug(match[1]));
      if (target) addEdge(edges, node.id, target.id, node.kind === 'wrapper' ? 'wraps' : 'references', match[0], config);
    }

    const helperRefs = [];
    for (const pattern of helperRegexes(config)) {
      for (const match of text.matchAll(pattern)) helperRefs.push(match[1]);
    }
    for (const helperRef of [...new Set(helperRefs)]) {
      const targetId = createScriptNode(resolveHelperReference(helperRef, node, config, text), config, nodes);
      addEdge(edges, node.id, targetId, 'uses-helper', helperRef, config);
    }

    for (const target of skillNodes) {
      if (target.id === node.id) continue;
      if (node.kind === 'wrapper' && canonicalByName.get(node.normalizedName)?.id === target.id) continue;
      const isConfigNode = /\.(?:json|jsonc|ya?ml)$/i.test(target.path);
      const exactFlags = target.rawName === target.rawName.toUpperCase() ? '' : 'i';
      const exact = new RegExp(`(^|[^A-Za-z0-9_-])${escapeRegExp(target.rawName)}([^A-Za-z0-9_-]|$)`, exactFlags);
      const pathMention = new RegExp(`${escapeRegExp(target.path)}(?:\\b|$)`, 'i');
      if (isConfigNode && !pathMention.test(text)) continue;
      if (!exact.test(text) && !pathMention.test(text)) continue;
      const evidence = evidenceNear(text, target.rawName) || evidenceNear(text, target.path);
      addEdge(edges, node.id, target.id, referenceTypeForEvidence(evidence), evidence, config);
    }
  }

  return edges.sort((a, b) => `${a.source}${a.target}${a.type}`.localeCompare(`${b.source}${b.target}${b.type}`));
}

function patternFromRule(rule) {
  if (rule.regex) return new RegExp(rule.regex, rule.flags || 'i');
  if (rule.pattern) return new RegExp(escapeRegExp(rule.pattern), rule.flags || 'i');
  return null;
}

function inferIssues(config, nodes, edges) {
  const issues = [];
  const byName = new Map();
  for (const node of nodes.filter((item) => item.kind !== 'helper-script')) {
    const list = byName.get(node.normalizedName) || [];
    list.push(node);
    byName.set(node.normalizedName, list);
  }

  for (const [name, matches] of byName.entries()) {
    const canonicalCount = matches.filter((node) => node.kind === 'canonical-skill').length;
    const onlyProviderDocs = matches.every((node) => node.kind === 'skill-doc');
    if (matches.length > 1 && canonicalCount !== 1) {
      if (onlyProviderDocs) continue;
      issues.push({
        severity: canonicalCount > 1 ? 'warn' : 'info',
        type: 'duplicate-name',
        message: `Multiple skill docs share name "${name}".`,
        paths: matches.map((node) => node.path),
      });
    }
  }

  const incoming = new Map(nodes.map((node) => [node.id, 0]));
  const outgoing = new Map(nodes.map((node) => [node.id, 0]));
  for (const edge of edges) {
    incoming.set(edge.target, (incoming.get(edge.target) || 0) + 1);
    outgoing.set(edge.source, (outgoing.get(edge.source) || 0) + 1);
  }
  for (const node of nodes) {
    if (node.kind === 'canonical-skill' && !incoming.get(node.id) && !outgoing.get(node.id)) {
      issues.push({
        severity: 'info',
        type: 'orphan-skill',
        message: `${node.name} has no inferred incoming or outgoing workflow edges.`,
        paths: [node.path],
      });
    }
    if (node.kind === 'missing-helper') {
      issues.push({
        severity: 'error',
        type: 'missing-helper',
        message: `Referenced helper does not exist: ${node.path}`,
        paths: [node.path],
      });
    }
  }

  for (const rule of config.rules.stalePatterns || []) {
    const pattern = patternFromRule(rule);
    if (!pattern) continue;
    for (const node of nodes.filter((item) => item.text)) {
      if (!pattern.test(node.text)) continue;
      issues.push({
        severity: rule.severity || 'warn',
        type: rule.id || 'stale-pattern',
        message: rule.message || `Pattern matched in ${node.path}.`,
        paths: [node.path],
      });
    }
  }

  return issues.sort((a, b) => `${a.severity}${a.type}${a.message}`.localeCompare(`${b.severity}${b.type}${b.message}`));
}

export function buildSkillGraph(options = {}) {
  const config = options.config?.rootDir ? options.config : loadConfig(options);
  const nodes = collectSkillNodes(config);
  const edges = inferEdges(config, nodes);
  const issues = inferIssues(config, nodes, edges);
  const publicNodes = nodes
    .map(({ text: _text, rawName: _rawName, ...node }) => node)
    .sort((a, b) => a.id.localeCompare(b.id));
  const graph = {
    generatedAt: 'deterministic',
    generator: 'skillgraph',
    configPath: config.configPath ? normalizePath(relative(config.rootDir, config.configPath)) : null,
    providers: selectedProviders(config).map(({ id, name, popularityRank, popularityBasis, roots }) => ({
      id,
      name,
      popularityRank,
      popularityBasis,
      roots,
    })),
    roots: config.roots,
    summary: {
      nodeCount: publicNodes.length,
      edgeCount: edges.length,
      issueCount: issues.length,
      byKind: publicNodes.reduce((acc, node) => {
        acc[node.kind] = (acc[node.kind] || 0) + 1;
        return acc;
      }, {}),
      byProvider: publicNodes.reduce((acc, node) => {
        for (const provider of node.providerNames || [node.providerName]) {
          acc[provider] = (acc[provider] || 0) + 1;
        }
        return acc;
      }, {}),
    },
    nodes: publicNodes,
    edges: edges.map(({ key: _key, ...edge }) => edge),
    issues,
  };
  return {
    ...graph,
    contentHash: contentHash({
      generator: graph.generator,
      configPath: graph.configPath,
      providers: graph.providers,
      roots: graph.roots,
      summary: graph.summary,
      nodes: graph.nodes,
      edges: graph.edges,
      issues: graph.issues,
    }),
  };
}

function mermaidId(index) {
  return `N${index}`;
}

function mermaidLabel(node) {
  return `${node.name}<br/><small>${node.kind}</small>`;
}

export function generateMermaid(graph) {
  const selectedEdges = graph.edges.filter((edge) => edge.type !== 'references');
  const connected = new Set(selectedEdges.flatMap((edge) => [edge.source, edge.target]));
  const nodes = graph.nodes.filter((node) => connected.has(node.id));
  const idMap = new Map(nodes.map((node, index) => [node.id, mermaidId(index)]));
  const lines = [
    'flowchart LR',
    '  classDef canonical fill:#dbeafe,stroke:#2563eb,color:#172554',
    '  classDef wrapper fill:#fef3c7,stroke:#d97706,color:#451a03',
    '  classDef helper fill:#dcfce7,stroke:#16a34a,color:#052e16',
    '  classDef doc fill:#f3f4f6,stroke:#6b7280,color:#111827',
  ];
  for (const node of nodes) lines.push(`  ${idMap.get(node.id)}["${mermaidLabel(node)}"]`);
  for (const edge of selectedEdges) {
    if (!idMap.has(edge.source) || !idMap.has(edge.target)) continue;
    lines.push(`  ${idMap.get(edge.source)} -- "${edge.label}" --> ${idMap.get(edge.target)}`);
  }
  for (const node of nodes) {
    const cls = node.kind === 'canonical-skill'
      ? 'canonical'
      : node.kind === 'wrapper'
        ? 'wrapper'
        : node.kind.includes('helper')
          ? 'helper'
          : 'doc';
    lines.push(`  class ${idMap.get(node.id)} ${cls}`);
  }
  return lines.join('\n');
}

export function generateMarkdown(graph) {
  const issueLines = graph.issues.length
    ? graph.issues.map((issue) => `- **${issue.severity.toUpperCase()} ${issue.type}:** ${issue.message}`).join('\n')
    : '- No issues detected.';
  const providerRows = graph.providers.length
    ? graph.providers
      .map((provider) => `| ${provider.popularityRank} | ${provider.name} | \`${provider.roots.join('`, `')}\` | ${provider.popularityBasis} |`)
      .join('\n')
    : '| - | Custom | - | No provider presets selected. |';
  const nodeRows = graph.nodes
    .map((node) => `| \`${node.name}\` | ${node.providerName} | ${node.kind} | \`${node.path}\` | ${node.tokenEstimate} |`)
    .join('\n');
  const edgeRows = graph.edges
    .map((edge) => {
      const source = graph.nodes.find((node) => node.id === edge.source)?.name || edge.source;
      const target = graph.nodes.find((node) => node.id === edge.target)?.name || edge.target;
      return `| \`${source}\` | ${edge.type} | \`${target}\` | ${edge.evidence || ''} |`;
    })
    .join('\n');
  return `${AUTO_MARKER}
# Skillgraph

Generated: ${graph.generatedAt}
Content hash: \`${graph.contentHash}\`

## Summary

- Nodes: ${graph.summary.nodeCount}
- Edges: ${graph.summary.edgeCount}
- Issues: ${graph.summary.issueCount}
- Kinds: ${Object.entries(graph.summary.byKind).map(([kind, count]) => `${kind}=${count}`).join(', ')}
- Providers: ${Object.entries(graph.summary.byProvider).map(([provider, count]) => `${provider}=${count}`).join(', ')}

## Provider Coverage

| Rank | Provider | Default roots | Basis |
| ---: | --- | --- | --- |
${providerRows}

## Workflow Map

\`\`\`mermaid
${generateMermaid(graph)}
\`\`\`

## Issues

${issueLines}

## Nodes

| Name | Provider | Kind | Path | Est. Tokens |
| --- | --- | --- | --- | ---: |
${nodeRows}

## Edges

| Source | Type | Target | Evidence |
| --- | --- | --- | --- |
${edgeRows}
`;
}

export function generateHtml(graph) {
  const data = JSON.stringify(graph);
  return `${AUTO_MARKER}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Skillgraph</title>
  <style>
    :root { color-scheme: light; --ink:#17201b; --muted:#5f6b63; --line:#d8ded8; --paper:#faf9f4; --panel:#fffefb; --blue:#2563eb; --amber:#d97706; --green:#16a34a; }
    body { margin:0; font:14px/1.45 ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color:var(--ink); background:var(--paper); }
    header { padding:18px 24px; border-bottom:1px solid var(--line); background:var(--panel); position:sticky; top:0; z-index:2; }
    h1 { margin:0 0 8px; font-size:22px; }
    .meta { color:var(--muted); display:flex; gap:14px; flex-wrap:wrap; }
    .controls { margin-top:14px; display:flex; gap:10px; flex-wrap:wrap; }
    input, select { min-height:36px; border:1px solid var(--line); border-radius:8px; padding:0 10px; background:white; }
    main { display:grid; grid-template-columns:minmax(0, 1fr) 360px; gap:18px; padding:18px; }
    #nodes { display:grid; grid-template-columns:repeat(auto-fill, minmax(220px, 1fr)); gap:12px; align-content:start; }
    .node { text-align:left; border:1px solid var(--line); background:var(--panel); border-radius:8px; padding:12px; cursor:pointer; min-height:116px; box-shadow:0 1px 0 rgba(24,32,28,.05); }
    .node:hover, .node.active { border-color:var(--blue); outline:2px solid rgba(37,99,235,.12); }
    .node h2 { margin:0 0 8px; font-size:15px; }
    .kind { display:inline-flex; min-height:22px; align-items:center; border-radius:999px; padding:0 8px; font-size:12px; background:#eef2ff; color:#1e3a8a; }
    .kind.wrapper { background:#fef3c7; color:#78350f; }
    .kind.helper-script { background:#dcfce7; color:#14532d; }
    .kind.skill-doc { background:#f3f4f6; color:#374151; }
    .path, .desc { color:var(--muted); overflow-wrap:anywhere; }
    aside { position:sticky; top:112px; align-self:start; background:var(--panel); border:1px solid var(--line); border-radius:10px; padding:14px; max-height:calc(100vh - 140px); overflow:auto; }
    .edge { border-top:1px solid var(--line); padding:10px 0; }
    .edge:first-child { border-top:0; }
    .edge strong { color:var(--blue); }
    .issue { border-left:3px solid var(--amber); padding:8px 10px; background:#fff7ed; margin:8px 0; }
    @media (max-width: 900px) { main { grid-template-columns:1fr; } aside { position:static; max-height:none; } }
  </style>
</head>
<body>
  <header>
    <h1>Skillgraph</h1>
    <div class="meta" id="summary"></div>
    <div class="controls">
      <input id="search" type="search" placeholder="Filter skills, paths, descriptions" />
      <select id="kind"><option value="">All kinds</option></select>
    </div>
  </header>
  <main>
    <section id="nodes" aria-label="Skill graph nodes"></section>
    <aside>
      <h2 id="detailTitle">Select a node</h2>
      <div id="detail"></div>
      <h3>Issues</h3>
      <div id="issues"></div>
    </aside>
  </main>
  <script>
    const graph = ${data};
    const nodes = graph.nodes;
    const edges = graph.edges;
    let selectedId = "";
    const byId = new Map(nodes.map(node => [node.id, node]));
    const search = document.getElementById('search');
    const kind = document.getElementById('kind');
    const nodeHost = document.getElementById('nodes');
    const detailTitle = document.getElementById('detailTitle');
    const detail = document.getElementById('detail');
    const issues = document.getElementById('issues');
    document.getElementById('summary').textContent = \`\${graph.summary.nodeCount} nodes | \${graph.summary.edgeCount} edges | \${graph.summary.issueCount} issues | hash \${graph.contentHash}\`;
    for (const value of [...new Set(nodes.map(node => node.kind))].sort()) {
      const option = document.createElement('option');
      option.value = value;
      option.textContent = value;
      kind.append(option);
    }
    function html(value) {
      return String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
    }
    function textFor(node) {
      return [node.name, node.providerName, node.kind, node.path, node.description].join(' ').toLowerCase();
    }
    function renderNodes() {
      const q = search.value.trim().toLowerCase();
      const k = kind.value;
      nodeHost.textContent = '';
      for (const node of nodes) {
        if (k && node.kind !== k) continue;
        if (q && !textFor(node).includes(q)) continue;
        const button = document.createElement('button');
        button.className = \`node \${selectedId === node.id ? 'active' : ''}\`;
        button.innerHTML = \`<h2>\${html(node.name)}</h2><span class="kind \${html(node.kind)}">\${html(node.kind)}</span><p class="desc">\${html(node.providerName)} · \${html(node.description || '')}</p><p class="path">\${html(node.path)}</p>\`;
        button.onclick = () => { selectedId = node.id; renderNodes(); renderDetail(); };
        nodeHost.append(button);
      }
    }
    function renderDetail() {
      const node = byId.get(selectedId);
      if (!node) {
        detailTitle.textContent = 'Select a node';
        detail.innerHTML = '<p class="path">Click a skill to see incoming and outgoing workflow edges.</p>';
        return;
      }
      detailTitle.textContent = node.name;
      const related = edges.filter(edge => edge.source === node.id || edge.target === node.id);
      detail.innerHTML = \`
        <p><span class="kind \${html(node.kind)}">\${html(node.kind)}</span></p>
        <p class="path">\${html(node.providerName)}</p>
        <p class="path">\${html(node.path)}</p>
        <p>\${html(node.description || '')}</p>
        <h3>Edges</h3>
        \${related.length ? related.map(edge => {
          const source = byId.get(edge.source)?.name || edge.source;
          const target = byId.get(edge.target)?.name || edge.target;
          return \`<div class="edge"><strong>\${html(edge.type)}</strong><br>\${html(source)} -&gt; \${html(target)}<p class="path">\${html(edge.evidence || '')}</p></div>\`;
        }).join('') : '<p class="path">No inferred edges.</p>'}
      \`;
    }
    function renderIssues() {
      issues.innerHTML = graph.issues.length
        ? graph.issues.map(issue => \`<div class="issue"><strong>\${html(issue.severity)} | \${html(issue.type)}</strong><br>\${html(issue.message)}</div>\`).join('')
        : '<p class="path">No issues detected.</p>';
    }
    search.addEventListener('input', renderNodes);
    kind.addEventListener('change', renderNodes);
    renderNodes();
    renderDetail();
    renderIssues();
  </script>
</body>
</html>
`;
}

export function writeOutputs(graph, outDir) {
  mkdirSync(outDir, { recursive: true });
  const files = {
    'skillgraph.json': jsonStable(graph),
    'SKILLGRAPH.md': generateMarkdown(graph),
    'skillgraph.html': generateHtml(graph),
  };
  for (const [name, content] of Object.entries(files)) {
    writeFileSync(join(outDir, name), content);
  }
  return files;
}

export function checkOutputs(graph, outDir) {
  const expected = {
    'skillgraph.json': jsonStable(graph),
    'SKILLGRAPH.md': generateMarkdown(graph),
    'skillgraph.html': generateHtml(graph),
  };
  const stale = [];
  for (const [name, content] of Object.entries(expected)) {
    const path = join(outDir, name);
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) stale.push(name);
  }
  return stale;
}

export function scanForbiddenTerms(rootDir, terms, exclude = DEFAULT_CONFIG.exclude) {
  const hits = [];
  function walk(currentAbs) {
    const repoPath = normalizePath(relative(rootDir, currentAbs));
    if (repoPath && isExcluded(repoPath, exclude)) return;
    const stat = statSync(currentAbs);
    if (stat.isDirectory()) {
      for (const entry of readdirSync(currentAbs)) walk(join(currentAbs, entry));
      return;
    }
    if (stat.size > 1024 * 1024) return;
    const text = readFileSync(currentAbs, 'utf8');
    const lines = text.split('\n');
    lines.forEach((line, index) => {
      for (const term of terms.filter(Boolean)) {
        if (line.toLowerCase().includes(term.toLowerCase())) {
          hits.push({ path: repoPath, line: index + 1, term });
        }
      }
    });
  }
  walk(rootDir);
  return hits;
}

function parseArgs(argv) {
  const args = { command: argv[2] || 'generate', roots: [] };
  for (let index = 3; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--config') args.configPath = argv[++index];
    else if (arg.startsWith('--config=')) args.configPath = arg.split('=')[1];
    else if (arg === '--root') args.rootDir = argv[++index];
    else if (arg.startsWith('--root=')) args.rootDir = arg.split('=')[1];
    else if (arg === '--out-dir') args.outDir = argv[++index];
    else if (arg.startsWith('--out-dir=')) args.outDir = arg.split('=')[1];
    else if (arg === '--skill-root') args.roots.push(argv[++index]);
    else if (arg.startsWith('--skill-root=')) args.roots.push(arg.split('=')[1]);
    else if (arg === '--terms-file') args.termsFile = argv[++index];
    else if (arg.startsWith('--terms-file=')) args.termsFile = arg.split('=')[1];
  }
  return args;
}

function printUsage() {
  console.log(`Skillgraph

Usage:
  skillgraph generate [--config skillgraph.config.json] [--root .]
  skillgraph check [--config skillgraph.config.json] [--root .]
  skillgraph audit [--config skillgraph.config.json] [--root .]
  skillgraph privacy-scan --terms-file docs/private-leak-terms.txt
`);
}

export async function runCli(argv = process.argv) {
  const args = parseArgs(argv);
  if (args.command === 'help' || args.command === '--help' || args.command === '-h') {
    printUsage();
    return;
  }
  if (args.command === 'privacy-scan') {
    const rootDir = resolve(args.rootDir || process.cwd());
    if (!args.termsFile) throw new Error('privacy-scan requires --terms-file');
    const terms = readFileSync(resolve(rootDir, args.termsFile), 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#'));
    const hits = scanForbiddenTerms(rootDir, terms, [...DEFAULT_CONFIG.exclude, normalizePath(args.termsFile)]);
    if (hits.length) {
      for (const hit of hits) console.error(`${hit.path}:${hit.line} contains forbidden term "${hit.term}"`);
      process.exit(1);
    }
    console.log(`Privacy scan passed: ${terms.length} terms`);
    return;
  }

  const config = loadConfig(args);
  const graph = buildSkillGraph({ config });
  if (args.command === 'generate') {
    writeOutputs(graph, config.outDirAbs);
    console.log(`Wrote skillgraph artifacts: ${normalizePath(relative(config.rootDir, config.outDirAbs))}`);
    console.log(`Nodes: ${graph.summary.nodeCount} | Edges: ${graph.summary.edgeCount} | Issues: ${graph.summary.issueCount}`);
    return;
  }
  if (args.command === 'check') {
    const stale = checkOutputs(graph, config.outDirAbs);
    if (stale.length) {
      console.error(`Skillgraph artifacts are stale: ${stale.join(', ')}`);
      console.error('Run: skillgraph generate');
      process.exit(1);
    }
    console.log(`Skillgraph artifacts are current: ${graph.summary.nodeCount} nodes, ${graph.summary.edgeCount} edges`);
    return;
  }
  if (args.command === 'audit') {
    console.log(JSON.stringify(graph.summary, null, 2));
    for (const issue of graph.issues) {
      const line = `${issue.severity.toUpperCase()} ${issue.type}: ${issue.message}`;
      if (issue.severity === 'error') console.error(line);
      else console.log(line);
    }
    if (graph.issues.some((issue) => issue.severity === 'error')) process.exit(1);
    return;
  }
  printUsage();
  process.exit(1);
}

export { DEFAULT_CONFIG, PROJECT_ROOT };
