import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, extname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = resolve(join(dirname(fileURLToPath(import.meta.url)), '..'));
const AUTO_MARKER = '<!-- auto-generated by skillgraph -->';

export const PROVIDER_PRESETS = [
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    popularityRank: 1,
    popularityBasis: 'Largest public user signal among covered tools.',
    roots: [
      '.github/copilot-instructions.md',
      '.github/instructions',
      '.github/prompts',
      '.github/agents',
      '.github/chatmodes',
      'AGENTS.md',
    ],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    popularityRank: 2,
    popularityBasis: 'Large AI editor adoption and native project rules.',
    roots: ['.cursor/rules', '.cursorrules', 'AGENTS.md'],
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    popularityRank: 3,
    popularityBasis: 'Major agentic coding tool with project memory, skills, commands, and subagents.',
    roots: ['CLAUDE.md', '.claude/CLAUDE.md', '.claude/skills', '.claude/commands', '.claude/agents', '.claude/rules'],
  },
  {
    id: 'openai-codex',
    name: 'OpenAI Codex',
    popularityRank: 4,
    popularityBasis: 'Native AGENTS.md workflow and strong public open-source repository signal.',
    roots: ['AGENTS.md', 'AGENTS.override.md'],
  },
  {
    id: 'cline',
    name: 'Cline',
    popularityRank: 5,
    popularityBasis: 'Popular open-source VS Code autonomous coding agent.',
    roots: ['.clinerules', '.cursorrules', '.windsurfrules', 'AGENTS.md', 'memory-bank'],
  },
  {
    id: 'augment-code',
    name: 'Augment Code',
    popularityRank: 6,
    popularityBasis: 'Commercial AI coding assistant with workspace rules, subagents, AGENTS.md, and review guidelines.',
    roots: ['.augment/rules', '.augment/agents', '.augment-guidelines', '.augment/code_review_guidelines.yaml', 'AGENTS.md', 'CLAUDE.md'],
  },
  {
    id: 'kilo-code',
    name: 'Kilo Code',
    popularityRank: 7,
    popularityBasis: 'Popular open-source VS Code agent with project rules and JSONC instructions.',
    roots: ['kilo.jsonc', 'kilo.json', '.kilo/rules', '.kilocode/rules', '.kilocode/rules-code', '.kilocoderules', 'AGENTS.md'],
  },
  {
    id: 'google-antigravity',
    name: 'Google Antigravity',
    popularityRank: 8,
    popularityBasis: 'Google agent-first IDE with GEMINI.md, AGENTS.md, rules, and workflows.',
    roots: ['GEMINI.md', 'AGENTS.md', '.agent/rules', '.agent/workflows', '.agents/rules', '.agents/workflows'],
  },
  {
    id: 'factory-ai',
    name: 'Factory AI',
    popularityRank: 9,
    popularityBasis: 'Factory Droids use AGENTS.md plus Factory rules, skills, commands, and custom droids.',
    roots: ['AGENTS.md', '.factory/rules', '.factory/skills', '.factory/commands', '.factory/droids'],
  },
  {
    id: 'agent-skills',
    name: 'Generic Agent Skills',
    popularityRank: 10,
    popularityBasis: 'Tool-agnostic skill roots used by multi-agent teams.',
    roots: ['.agents/skills'],
  },
];

const DEFAULT_CONFIG = {
  providers: PROVIDER_PRESETS.map((provider) => provider.id),
  roots: [],
  outDir: 'docs/skills',
  canonicalRoots: ['.agents/skills'],
  wrapperRoots: ['.claude/skills'],
  exclude: ['**/node_modules/**', '**/.git/**'],
  instructionExtensions: ['.md', '.mdc', '.txt', '.json', '.jsonc', '.yaml', '.yml'],
  helperPatterns: [
    'scripts/**/*.mjs',
    'scripts/**/*.js',
    'scripts/**/*.cjs',
    'scripts/**/*.sh',
    'bin/**/*.mjs',
  ],
  privacy: {
    includeEvidence: true,
    redactTerms: [],
  },
  rules: {
    stalePatterns: [],
  },
};

function normalizePath(path) {
  return path.split(/[\\/]+/).join('/');
}

function slug(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'node';
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function jsonStable(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function contentHash(value) {
  return createHash('sha256').update(jsonStable(value)).digest('hex').slice(0, 12);
}

function deepMerge(base, override) {
  if (!override || typeof override !== 'object') return base;
  const output = { ...base };
  for (const [key, value] of Object.entries(override)) {
    if (Array.isArray(value)) output[key] = value;
    else if (value && typeof value === 'object' && !Array.isArray(value)) {
      output[key] = deepMerge(base[key] || {}, value);
    } else output[key] = value;
  }
  return output;
}

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function unique(values) {
  return [...new Set(values.filter(Boolean).map(normalizePath))];
}

function selectedProviders(config) {
  const selected = new Set(config.providers || []);
  return PROVIDER_PRESETS
    .filter((provider) => selected.has(provider.id))
    .sort((a, b) => a.popularityRank - b.popularityRank);
}

function expandProviderRoots(config) {
  return unique([
    ...selectedProviders(config).flatMap((provider) => provider.roots),
    ...(config.roots || []),
  ]);
}

function providersForRoot(rootRel, config) {
  const root = normalizePath(rootRel);
  return selectedProviders(config).filter((provider) => provider.roots.map(normalizePath).includes(root));
}

export function loadConfig(options = {}) {
  const rootDir = resolve(options.rootDir || process.cwd());
  const configPath = options.configPath
    ? resolve(rootDir, options.configPath)
    : resolve(rootDir, 'skillgraph.config.json');
  const config = existsSync(configPath)
    ? deepMerge(DEFAULT_CONFIG, readJson(configPath))
    : { ...DEFAULT_CONFIG };
  if (options.outDir) config.outDir = options.outDir;
  if (options.roots?.length) config.roots = options.roots;
  config.roots = expandProviderRoots(config);
  return {
    ...config,
    rootDir,
    outDirAbs: resolve(rootDir, config.outDir),
    configPath: existsSync(configPath) ? configPath : null,
  };
}

export function parseFrontmatter(text) {
  if (!text.startsWith('---\n')) return {};
  const end = text.indexOf('\n---', 4);
  if (end === -1) return {};
  const raw = text.slice(4, end).trim();
  const frontmatter = {};
  for (const line of raw.split('\n')) {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) continue;
    let value = match[2].trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    frontmatter[match[1]] = value;
  }
  return frontmatter;
}

function globToRegExp(pattern) {
  const input = normalizePath(pattern);
  let output = '';
  for (let index = 0; index < input.length; index += 1) {
    const char = input[index];
    const next = input[index + 1];
    if (char === '*' && next === '*') {
      output += '.*';
      index += 1;
    } else if (char === '*') {
      output += '[^/]*';
    } else if ('\\.+?^${}()|[]'.includes(char)) {
      output += `\\${char}`;
    } else {
      output += char;
    }
  }
  return new RegExp(`^${output}$`);
}

function isExcluded(repoPath, excludePatterns) {
  return excludePatterns.some((pattern) => globToRegExp(pattern).test(repoPath));
}

function isInstructionFile(filePath, config) {
  return config.instructionExtensions.includes(extname(filePath).toLowerCase());
}

function walkInstructionFiles(rootAbs, rootDir, config, currentAbs = rootAbs, result = []) {
  if (!existsSync(currentAbs)) return result;
  const stat = statSync(currentAbs);
  if (stat.isFile()) {
    result.push(currentAbs);
    return result;
  }
  for (const entry of readdirSync(currentAbs)) {
    const fullPath = join(currentAbs, entry);
    const repoPath = normalizePath(relative(rootDir, fullPath));
    if (isExcluded(repoPath, config.exclude)) continue;
    const entryStat = statSync(fullPath);
    if (entryStat.isDirectory()) {
      walkInstructionFiles(rootAbs, rootDir, config, fullPath, result);
    } else if (isInstructionFile(entry, config)) {
      result.push(fullPath);
    }
  }
  return result;
}

function inferNameFromPath(relativePath, frontmatter) {
  if (frontmatter.name) return frontmatter.name;
  const normalized = normalizePath(relativePath);
  const parts = normalized.split('/');
  if (basename(normalized) === 'SKILL.md' && parts.length >= 2) {
    return parts[parts.length - 2];
  }
  return basename(normalized, extname(normalized));
}

function classifyNode(rootRel, relativePath, frontmatter, text, config) {
  const normalizedRoot = normalizePath(rootRel);
  const normalizedPath = normalizePath(relativePath);
  const canonicalRoots = config.canonicalRoots.map(normalizePath);
  const wrapperRoots = config.wrapperRoots.map(normalizePath);
  if (canonicalRoots.includes(normalizedRoot) && basename(normalizedPath) === 'SKILL.md') {
    return 'canonical-skill';
  }
  const mentionsCanonicalRoot = canonicalRoots.some((root) => text.includes(`${root}/`));
  if (
    wrapperRoots.includes(normalizedRoot) &&
    (text.includes('Canonical skill instructions live at:') || mentionsCanonicalRoot)
  ) {
    return 'wrapper';
  }
  if (basename(normalizedPath) === 'SKILL.md' || frontmatter.name) {
    return 'skill';
  }
  return 'skill-doc';
}

function firstMeaningfulLine(text) {
  return text
    .split('\n')
    .map((line) => line.trim())
    .find((line) => line && !line.startsWith('---') && !line.startsWith('<!--') && !line.startsWith('#'));
}

function redact(value, terms = []) {
  let output = String(value ?? '');
  for (const term of terms.filter(Boolean)) {
    output = output.replaceAll(term, '[redacted]');
  }
  return output;
}

function extractDescription(text, frontmatter, config) {
  const description = frontmatter.description || firstMeaningfulLine(text) || '';
  return redact(description.slice(0, 220), config.privacy.redactTerms);
}

function collectSkillNodes(config) {
  const nodes = [];
  for (const rootRel of config.roots) {
    const rootAbs = resolve(config.rootDir, rootRel);
    const rootIsFile = existsSync(rootAbs) && statSync(rootAbs).isFile();
    for (const fullPath of walkInstructionFiles(rootAbs, config.rootDir, config)) {
      const relativeToRoot = rootIsFile
        ? basename(fullPath)
        : normalizePath(relative(rootAbs, fullPath));
      const repoPath = normalizePath(relative(config.rootDir, fullPath));
      const text = readFileSync(fullPath, 'utf8');
      const frontmatter = parseFrontmatter(text);
      const name = inferNameFromPath(relativeToRoot, frontmatter);
      const kind = classifyNode(rootRel, relativeToRoot, frontmatter, text, config);
      const providers = providersForRoot(rootRel, config);
      const providerNames = providers.length ? providers.map((provider) => provider.name) : ['Custom'];
      const id = rootIsFile ? `file:${repoPath}` : `${normalizePath(rootRel)}:${relativeToRoot}`;
      nodes.push({
        id,
        name: redact(name, config.privacy.redactTerms),
        rawName: name,
        normalizedName: slug(name),
        label: redact(name, config.privacy.redactTerms),
        kind,
        providers: providers.length ? providers.map((provider) => provider.id) : ['custom'],
        provider: providers[0]?.id || 'custom',
        providerNames,
        providerName: providerNames.join(' / '),
        popularityRank: providers[0]?.popularityRank || 999,
        root: normalizePath(rootRel),
        path: repoPath,
        description: extractDescription(text, frontmatter, config),
        bytes: Buffer.byteLength(text, 'utf8'),
        tokenEstimate: Math.ceil(Buffer.byteLength(text, 'utf8') / 4),
        frontmatter: Object.fromEntries(
          Object.entries(frontmatter).map(([key, value]) => [key, redact(value, config.privacy.redactTerms)]),
        ),
        text,
      });
    }
  }
  return nodes.sort((a, b) => a.path.localeCompare(b.path));
}

function addEdge(edges, source, target, type, evidence = '', config = DEFAULT_CONFIG) {
  if (!source || !target || source === target) return;
  const key = `${source}->${target}:${type}`;
  if (edges.some((edge) => edge.key === key)) return;
  edges.push({
    key,
    id: `edge-${edges.length + 1}`,
    source,
    target,
    type,
    label: type.replaceAll('-', ' '),
    evidence: config.privacy.includeEvidence
      ? redact(evidence.replace(/\s+/g, ' ').trim().slice(0, 220), config.privacy.redactTerms)
      : '',
  });
}

function evidenceNear(text, needle) {
  const index = text.toLowerCase().indexOf(String(needle).toLowerCase());
  if (index === -1) return '';
  return text.slice(Math.max(0, index - 90), Math.min(text.length, index + String(needle).length + 90));
}

function referenceTypeForEvidence(evidence) {
  if (/(before returning|route through|orchestrates|delegate|depends|invoke|run|use|calls)/i.test(evidence)) {
    return 'calls';
  }
  return 'references';
}

function createScriptNode(scriptPath, config, nodes) {
  const normalized = normalizePath(scriptPath).replace(/[.,;:]+$/g, '');
  const existing = nodes.find((node) => node.id === `script:${normalized}`);
  if (existing) return existing.id;
  const abs = resolve(config.rootDir, normalized);
  const bytes = existsSync(abs) ? Buffer.byteLength(readFileSync(abs, 'utf8'), 'utf8') : 0;
  nodes.push({
    id: `script:${normalized}`,
    name: basename(normalized),
    rawName: basename(normalized),
    normalizedName: slug(basename(normalized)),
    label: basename(normalized),
    kind: existsSync(abs) ? 'helper-script' : 'missing-helper',
    providers: ['helper'],
    provider: 'helper',
    providerNames: ['Helper Script'],
    providerName: 'Helper Script',
    popularityRank: 999,
    root: dirname(normalized),
    path: normalized,
    description: existsSync(abs) ? 'Helper script referenced by a skill.' : 'Referenced helper script was not found.',
    bytes,
    tokenEstimate: Math.ceil(bytes / 4),
    frontmatter: {},
  });
  return `script:${normalized}`;
}

function resolveHelperReference(candidate, sourceNode, config, sourceText = '') {
  const normalized = normalizePath(candidate).replace(/[.,;:]+$/g, '');
  if (!normalized.startsWith('scripts/')) return normalized;
  const matchingLines = sourceText
    .split('\n')
    .filter((line) => line.includes(candidate) || line.includes(normalized));
  for (const line of matchingLines) {
    const cdMatch = line.match(/\bcd\s+(["']?)([^"';&|`\s]+)\1/);
    if (!cdMatch) continue;
    const cwd = normalizePath(cdMatch[2]).replace(/^\.\//, '').replace(/^\.\.\//, '');
    const cwdCandidate = normalizePath(join(cwd, normalized));
    if (existsSync(resolve(config.rootDir, cwdCandidate))) return cwdCandidate;
  }
  if (existsSync(resolve(config.rootDir, normalized))) return normalized;
  const sourceRelative = normalizePath(join(dirname(sourceNode.path), normalized));
  if (existsSync(resolve(config.rootDir, sourceRelative))) return sourceRelative;
  return normalized;
}

function helperRegexes(config) {
  const roots = [...new Set([...config.roots, ...config.canonicalRoots, ...config.wrapperRoots])].map(normalizePath);
  const rootPattern = roots.map(escapeRegExp).join('|');
  return [
    new RegExp(`((${rootPattern})/[^\\s\`'")]+/scripts/[^\\s\`'")]+)`, 'g'),
    /(?:^|[\s`'"])((?:[A-Za-z0-9_.-]+\/)+scripts\/[A-Za-z0-9_./-]+\.(?:mjs|cjs|js|sh|ts))/g,
    /(?:^|[\s`'"])((?:scripts|bin)\/[A-Za-z0-9_./-]+\.(?:mjs|cjs|js|sh|ts))/g,
  ];
}

function inferEdges(config, nodes) {
  const edges = [];
  const skillNodes = nodes.filter((node) => node.text);
  const canonicalByName = new Map();
  for (const node of skillNodes) {
    if (node.kind === 'canonical-skill' && !canonicalByName.has(node.normalizedName)) {
      canonicalByName.set(node.normalizedName, node);
    }
  }

  const canonicalRootPattern = config.canonicalRoots.map(escapeRegExp).join('|');
  const canonicalRefRegex = new RegExp(`(?:${canonicalRootPattern})/([^/\\s\`'")]+)/SKILL\\.md`, 'g');

  for (const node of skillNodes) {
    const text = node.text;
    for (const match of text.matchAll(canonicalRefRegex)) {
      const target = canonicalByName.get(slug(match[1]));
      if (target) addEdge(edges, node.id, target.id, node.kind === 'wrapper' ? 'wraps' : 'references', match[0], config);
    }

    const helperRefs = [];
    for (const pattern of helperRegexes(config)) {
      for (const match of text.matchAll(pattern)) helperRefs.push(match[1]);
    }
    for (const helperRef of [...new Set(helperRefs)]) {
      const targetId = createScriptNode(resolveHelperReference(helperRef, node, config, text), config, nodes);
      addEdge(edges, node.id, targetId, 'uses-helper', helperRef, config);
    }

    for (const target of skillNodes) {
      if (target.id === node.id) continue;
      if (node.kind === 'wrapper' && canonicalByName.get(node.normalizedName)?.id === target.id) continue;
      const isConfigNode = /\.(?:json|jsonc|ya?ml)$/i.test(target.path);
      const exactFlags = target.rawName === target.rawName.toUpperCase() ? '' : 'i';
      const exact = new RegExp(`(^|[^A-Za-z0-9_-])${escapeRegExp(target.rawName)}([^A-Za-z0-9_-]|$)`, exactFlags);
      const pathMention = new RegExp(`${escapeRegExp(target.path)}(?:\\b|$)`, 'i');
      if (isConfigNode && !pathMention.test(text)) continue;
      if (!exact.test(text) && !pathMention.test(text)) continue;
      const evidence = evidenceNear(text, target.rawName) || evidenceNear(text, target.path);
      addEdge(edges, node.id, target.id, referenceTypeForEvidence(evidence), evidence, config);
    }
  }

  return edges.sort((a, b) => `${a.source}${a.target}${a.type}`.localeCompare(`${b.source}${b.target}${b.type}`));
}

function patternFromRule(rule) {
  if (rule.regex) return new RegExp(rule.regex, rule.flags || 'i');
  if (rule.pattern) return new RegExp(escapeRegExp(rule.pattern), rule.flags || 'i');
  return null;
}

function inferIssues(config, nodes, edges) {
  const issues = [];
  const byName = new Map();
  for (const node of nodes.filter((item) => item.kind !== 'helper-script')) {
    const list = byName.get(node.normalizedName) || [];
    list.push(node);
    byName.set(node.normalizedName, list);
  }

  for (const [name, matches] of byName.entries()) {
    const canonicalCount = matches.filter((node) => node.kind === 'canonical-skill').length;
    const onlyProviderDocs = matches.every((node) => node.kind === 'skill-doc');
    if (matches.length > 1 && canonicalCount !== 1) {
      if (onlyProviderDocs) continue;
      issues.push({
        severity: canonicalCount > 1 ? 'warn' : 'info',
        type: 'duplicate-name',
        message: `Multiple skill docs share name "${name}".`,
        paths: matches.map((node) => node.path),
      });
    }
  }

  const incoming = new Map(nodes.map((node) => [node.id, 0]));
  const outgoing = new Map(nodes.map((node) => [node.id, 0]));
  for (const edge of edges) {
    incoming.set(edge.target, (incoming.get(edge.target) || 0) + 1);
    outgoing.set(edge.source, (outgoing.get(edge.source) || 0) + 1);
  }
  for (const node of nodes) {
    if (node.kind === 'canonical-skill' && !incoming.get(node.id) && !outgoing.get(node.id)) {
      issues.push({
        severity: 'info',
        type: 'orphan-skill',
        message: `${node.name} has no inferred incoming or outgoing workflow edges.`,
        paths: [node.path],
      });
    }
    if (node.kind === 'missing-helper') {
      issues.push({
        severity: 'error',
        type: 'missing-helper',
        message: `Referenced helper does not exist: ${node.path}`,
        paths: [node.path],
      });
    }
  }

  for (const rule of config.rules.stalePatterns || []) {
    const pattern = patternFromRule(rule);
    if (!pattern) continue;
    for (const node of nodes.filter((item) => item.text)) {
      if (!pattern.test(node.text)) continue;
      issues.push({
        severity: rule.severity || 'warn',
        type: rule.id || 'stale-pattern',
        message: rule.message || `Pattern matched in ${node.path}.`,
        paths: [node.path],
      });
    }
  }

  return issues.sort((a, b) => `${a.severity}${a.type}${a.message}`.localeCompare(`${b.severity}${b.type}${b.message}`));
}

export function buildSkillGraph(options = {}) {
  const config = options.config?.rootDir ? options.config : loadConfig(options);
  const nodes = collectSkillNodes(config);
  const edges = inferEdges(config, nodes);
  const issues = inferIssues(config, nodes, edges);
  const publicNodes = nodes
    .map(({ text: _text, rawName: _rawName, ...node }) => node)
    .sort((a, b) => a.id.localeCompare(b.id));
  const graph = {
    generatedAt: 'deterministic',
    generator: 'skillgraph',
    configPath: config.configPath ? normalizePath(relative(config.rootDir, config.configPath)) : null,
    providers: selectedProviders(config).map(({ id, name, popularityRank, popularityBasis, roots }) => ({
      id,
      name,
      popularityRank,
      popularityBasis,
      roots,
    })),
    roots: config.roots,
    summary: {
      nodeCount: publicNodes.length,
      edgeCount: edges.length,
      issueCount: issues.length,
      byKind: publicNodes.reduce((acc, node) => {
        acc[node.kind] = (acc[node.kind] || 0) + 1;
        return acc;
      }, {}),
      byProvider: publicNodes.reduce((acc, node) => {
        for (const provider of node.providerNames || [node.providerName]) {
          acc[provider] = (acc[provider] || 0) + 1;
        }
        return acc;
      }, {}),
    },
    nodes: publicNodes,
    edges: edges.map(({ key: _key, ...edge }) => edge),
    issues,
  };
  return {
    ...graph,
    contentHash: contentHash({
      generator: graph.generator,
      configPath: graph.configPath,
      providers: graph.providers,
      roots: graph.roots,
      summary: graph.summary,
      nodes: graph.nodes,
      edges: graph.edges,
      issues: graph.issues,
    }),
  };
}

function mermaidId(index) {
  return `N${index}`;
}

function mermaidLabel(node) {
  return `${node.name}<br/><small>${node.kind}</small>`;
}

export function generateMermaid(graph) {
  const selectedEdges = graph.edges.filter((edge) => edge.type !== 'references');
  const connected = new Set(selectedEdges.flatMap((edge) => [edge.source, edge.target]));
  const nodes = graph.nodes.filter((node) => connected.has(node.id));
  const idMap = new Map(nodes.map((node, index) => [node.id, mermaidId(index)]));
  const lines = [
    'flowchart LR',
    '  classDef canonical fill:#dbeafe,stroke:#2563eb,color:#172554',
    '  classDef wrapper fill:#fef3c7,stroke:#d97706,color:#451a03',
    '  classDef helper fill:#dcfce7,stroke:#16a34a,color:#052e16',
    '  classDef doc fill:#f3f4f6,stroke:#6b7280,color:#111827',
  ];
  for (const node of nodes) lines.push(`  ${idMap.get(node.id)}["${mermaidLabel(node)}"]`);
  for (const edge of selectedEdges) {
    if (!idMap.has(edge.source) || !idMap.has(edge.target)) continue;
    lines.push(`  ${idMap.get(edge.source)} -- "${edge.label}" --> ${idMap.get(edge.target)}`);
  }
  for (const node of nodes) {
    const cls = node.kind === 'canonical-skill'
      ? 'canonical'
      : node.kind === 'wrapper'
        ? 'wrapper'
        : node.kind.includes('helper')
          ? 'helper'
          : 'doc';
    lines.push(`  class ${idMap.get(node.id)} ${cls}`);
  }
  return lines.join('\n');
}

export function generateMarkdown(graph) {
  const issueLines = graph.issues.length
    ? graph.issues.map((issue) => `- **${issue.severity.toUpperCase()} ${issue.type}:** ${issue.message}`).join('\n')
    : '- No issues detected.';
  const providerRows = graph.providers.length
    ? graph.providers
      .map((provider) => `| ${provider.popularityRank} | ${provider.name} | \`${provider.roots.join('`, `')}\` | ${provider.popularityBasis} |`)
      .join('\n')
    : '| - | Custom | - | No provider presets selected. |';
  const nodeRows = graph.nodes
    .map((node) => `| \`${node.name}\` | ${node.providerName} | ${node.kind} | \`${node.path}\` | ${node.tokenEstimate} |`)
    .join('\n');
  const edgeRows = graph.edges
    .map((edge) => {
      const source = graph.nodes.find((node) => node.id === edge.source)?.name || edge.source;
      const target = graph.nodes.find((node) => node.id === edge.target)?.name || edge.target;
      return `| \`${source}\` | ${edge.type} | \`${target}\` | ${edge.evidence || ''} |`;
    })
    .join('\n');
  return `${AUTO_MARKER}
# Skillgraph

Generated: ${graph.generatedAt}
Content hash: \`${graph.contentHash}\`

## Summary

- Nodes: ${graph.summary.nodeCount}
- Edges: ${graph.summary.edgeCount}
- Issues: ${graph.summary.issueCount}
- Kinds: ${Object.entries(graph.summary.byKind).map(([kind, count]) => `${kind}=${count}`).join(', ')}
- Providers: ${Object.entries(graph.summary.byProvider).map(([provider, count]) => `${provider}=${count}`).join(', ')}

## Provider Coverage

| Rank | Provider | Default roots | Basis |
| ---: | --- | --- | --- |
${providerRows}

## Workflow Map

\`\`\`mermaid
${generateMermaid(graph)}
\`\`\`

## Issues

${issueLines}

## Nodes

| Name | Provider | Kind | Path | Est. Tokens |
| --- | --- | --- | --- | ---: |
${nodeRows}

## Edges

| Source | Type | Target | Evidence |
| --- | --- | --- | --- |
${edgeRows}
`;
}

export function generateHtml(graph) {
  const data = JSON.stringify(graph);
  return `${AUTO_MARKER}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Skillgraph</title>
  <style>
    :root {
      color-scheme: light;
      --ink:#171a1f;
      --muted:#667085;
      --line:#d9dee7;
      --paper:#f6f4ee;
      --panel:#fffefa;
      --blue:#2d5be3;
      --green:#0d9488;
      --amber:#d97706;
      --red:#dc2626;
      --shadow:0 12px 40px rgba(23,26,31,.10);
    }
    * { box-sizing:border-box; }
    body {
      margin:0;
      min-height:100vh;
      color:var(--ink);
      background:
        linear-gradient(90deg, rgba(45,91,227,.05) 1px, transparent 1px),
        linear-gradient(rgba(45,91,227,.04) 1px, transparent 1px),
        var(--paper);
      background-size:28px 28px;
      font:14px/1.45 ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }
    button, input, select { font:inherit; }
    .app { min-height:100vh; display:grid; grid-template-rows:auto minmax(0, 1fr); }
    header {
      position:sticky;
      top:0;
      z-index:5;
      display:grid;
      grid-template-columns:minmax(220px, 1fr) auto;
      gap:18px;
      padding:18px 22px;
      border-bottom:1px solid var(--line);
      background:rgba(255,254,250,.94);
      backdrop-filter:blur(14px);
    }
    h1, h2, h3, p { margin-top:0; }
    h1 { margin-bottom:4px; font-size:24px; letter-spacing:0; }
    h2 { margin-bottom:10px; font-size:15px; }
    h3 { margin-bottom:8px; font-size:13px; text-transform:uppercase; color:var(--muted); letter-spacing:.08em; }
    .eyebrow { margin:0 0 2px; color:var(--green); font-size:12px; font-weight:800; text-transform:uppercase; letter-spacing:.09em; }
    .lede { max-width:720px; margin:0; color:var(--muted); }
    .metrics { display:flex; gap:8px; flex-wrap:wrap; align-content:start; justify-content:flex-end; }
    .metric { min-width:86px; padding:9px 11px; border:1px solid var(--line); border-radius:8px; background:white; box-shadow:0 1px 0 rgba(23,26,31,.04); }
    .metric strong { display:block; font-size:18px; line-height:1.05; }
    .metric span { color:var(--muted); font-size:12px; }
    .workspace {
      display:grid;
      grid-template-columns:290px minmax(0, 1fr) 350px;
      gap:14px;
      min-height:0;
      padding:14px;
    }
    .panel {
      min-width:0;
      border:1px solid var(--line);
      border-radius:8px;
      background:var(--panel);
      box-shadow:var(--shadow);
    }
    .left, .right { display:flex; flex-direction:column; height:calc(100vh - 164px); min-height:560px; overflow:hidden; }
    .panel-head { padding:14px; border-bottom:1px solid var(--line); background:linear-gradient(180deg, #fffefa, #f9faf6); }
    .filters { display:grid; gap:9px; }
    .filters input, .filters select {
      width:100%;
      min-height:38px;
      border:1px solid var(--line);
      border-radius:7px;
      padding:0 10px;
      background:white;
      color:var(--ink);
    }
    .node-list, .issue-list { overflow:auto; padding:10px; }
    .node-list { display:grid; gap:8px; }
    .node-row {
      width:100%;
      min-height:70px;
      text-align:left;
      border:1px solid var(--line);
      border-radius:8px;
      padding:9px 10px;
      background:white;
      color:var(--ink);
      cursor:pointer;
    }
    .node-row:hover, .node-row.active { border-color:var(--blue); outline:2px solid rgba(45,91,227,.12); }
    .row-title { display:block; margin-bottom:4px; font-weight:750; overflow-wrap:anywhere; }
    .row-meta, .path, .muted { color:var(--muted); font-size:12px; overflow-wrap:anywhere; }
    .map-panel { position:relative; display:grid; grid-template-rows:auto minmax(0, 1fr); height:calc(100vh - 164px); min-height:560px; overflow:hidden; }
    .map-toolbar {
      display:flex;
      gap:8px;
      align-items:center;
      justify-content:space-between;
      padding:10px;
      border-bottom:1px solid var(--line);
      background:#fffefa;
    }
    .tool-group { display:flex; gap:8px; align-items:center; flex-wrap:wrap; }
    .tool-button {
      min-height:34px;
      border:1px solid var(--line);
      border-radius:7px;
      padding:0 10px;
      background:white;
      color:var(--ink);
      cursor:pointer;
    }
    .tool-button:hover { border-color:var(--blue); color:var(--blue); }
    .map-canvas { min-width:0; min-height:0; height:100%; overflow:hidden; position:relative; background:linear-gradient(180deg, #fbfcff, #f7f4eb); }
    #graphSvg { display:block; width:100%; height:100%; cursor:grab; }
    #graphSvg.dragging { cursor:grabbing; }
    .edge-path { fill:none; stroke:#9aa4b2; stroke-width:1.6; opacity:.74; }
    .edge-path.calls { stroke:var(--blue); stroke-width:2.2; }
    .edge-path.wraps { stroke:var(--amber); stroke-width:2.2; }
    .edge-path.uses-helper { stroke:var(--green); stroke-width:2.2; }
    .edge-path.references { stroke-dasharray:5 4; opacity:.42; }
    .edge-path.dim, .node-g.dim { opacity:.12; }
    .edge-label { fill:#475467; font-size:11px; paint-order:stroke; stroke:#fffefa; stroke-width:4px; stroke-linejoin:round; }
    .node-rect { fill:white; stroke:#bac4d3; stroke-width:1.3; rx:8; filter:url(#cardShadow); }
    .node-g.canonical-skill .node-rect { stroke:var(--blue); fill:#eef4ff; }
    .node-g.wrapper .node-rect { stroke:var(--amber); fill:#fff7ed; }
    .node-g.skill .node-rect { stroke:var(--green); fill:#ecfdf5; }
    .node-g.helper-script .node-rect { stroke:#16a34a; fill:#f0fdf4; }
    .node-g.missing-helper .node-rect { stroke:var(--red); fill:#fef2f2; }
    .node-g.issue .node-rect { stroke:var(--red); stroke-width:2.3; }
    .node-g.selected .node-rect { stroke:#111827; stroke-width:2.5; }
    .node-title { fill:#111827; font-size:13px; font-weight:760; }
    .node-subtitle { fill:#667085; font-size:10.5px; }
    .node-kind { fill:#344054; font-size:10.5px; font-weight:650; text-transform:uppercase; }
    .legend { display:flex; gap:8px; flex-wrap:wrap; color:var(--muted); font-size:12px; }
    .legend span { display:inline-flex; align-items:center; gap:5px; }
    .swatch { width:10px; height:10px; border-radius:3px; background:var(--blue); }
    .swatch.wraps { background:var(--amber); }
    .swatch.helper { background:var(--green); }
    .swatch.ref { background:#9aa4b2; }
    .inspector-body { overflow:auto; padding:14px; }
    .badge-row { display:flex; gap:6px; flex-wrap:wrap; margin-bottom:10px; }
    .badge { display:inline-flex; align-items:center; min-height:23px; border-radius:999px; padding:0 8px; background:#eef2ff; color:#1e3a8a; font-size:12px; font-weight:650; }
    .badge.err { background:#fef2f2; color:#991b1b; }
    .detail-card { padding:11px; border:1px solid var(--line); border-radius:8px; background:white; margin-bottom:10px; }
    .edge-item, .issue {
      border:1px solid var(--line);
      border-left:4px solid var(--blue);
      border-radius:8px;
      padding:9px 10px;
      background:white;
      margin-bottom:8px;
    }
    .edge-item.wraps { border-left-color:var(--amber); }
    .edge-item.uses-helper { border-left-color:var(--green); }
    .edge-item.references { border-left-color:#98a2b3; }
    .issue { border-left-color:var(--amber); }
    .issue.error { border-left-color:var(--red); }
    .empty { padding:20px; color:var(--muted); text-align:center; }
    @media (max-width: 1180px) {
      header { grid-template-columns:1fr; }
      .metrics { justify-content:flex-start; }
      .workspace { grid-template-columns:260px minmax(0, 1fr); }
      .right { grid-column:1 / -1; height:420px; min-height:420px; }
    }
    @media (max-width: 760px) {
      header { position:static; padding:14px; }
      .workspace { grid-template-columns:1fr; padding:10px; }
      .map-panel { height:620px; min-height:620px; }
      .left { height:520px; min-height:520px; }
      .right { height:560px; min-height:560px; }
      .metric { min-width:72px; }
    }
  </style>
</head>
<body>
  <div class="app">
    <header>
      <div>
        <p class="eyebrow">Interactive skill map</p>
        <h1>Skillgraph</h1>
        <p class="lede">Explore every agent skill, provider instruction file, wrapper, helper script, dependency edge, and issue in one generated UI.</p>
      </div>
      <div class="metrics" id="metrics"></div>
    </header>
    <main class="workspace">
      <aside class="panel left">
        <div class="panel-head">
          <h2>Find Skills</h2>
          <div class="filters">
            <input id="search" type="search" placeholder="Search skills, paths, providers" />
            <select id="provider"><option value="">All providers</option></select>
            <select id="kind"><option value="">All kinds</option></select>
            <select id="edgeType"><option value="">All edge types</option></select>
          </div>
        </div>
        <div class="node-list" id="nodeList" aria-label="Skill nodes"></div>
      </aside>
      <section class="panel map-panel" aria-label="Skill graph visualization">
        <div class="map-toolbar">
          <div class="tool-group">
            <button class="tool-button" id="fit" type="button">Fit all</button>
            <button class="tool-button" id="zoomIn" type="button">Zoom in</button>
            <button class="tool-button" id="zoomOut" type="button">Zoom out</button>
            <button class="tool-button" id="reset" type="button">Reset filters</button>
          </div>
          <div class="legend">
            <span><i class="swatch"></i>calls</span>
            <span><i class="swatch wraps"></i>wraps</span>
            <span><i class="swatch helper"></i>helper</span>
            <span><i class="swatch ref"></i>reference</span>
          </div>
        </div>
        <div class="map-canvas">
          <svg id="graphSvg" role="img" aria-label="Interactive skill dependency graph"></svg>
        </div>
      </section>
      <aside class="panel right">
        <div class="panel-head">
          <h2 id="detailTitle">Select a skill</h2>
          <p class="muted" id="detailSubtitle">Click a node or list item to inspect dependencies.</p>
        </div>
        <div class="inspector-body">
          <div id="detail"></div>
          <h3>Open Issues</h3>
          <div class="issue-list" id="issues"></div>
        </div>
      </aside>
    </main>
  </div>
  <script>
    const graph = ${data};
    const nodes = graph.nodes.slice();
    const edges = graph.edges.slice();
    const byId = new Map(nodes.map(node => [node.id, node]));
    const issuePaths = new Set(graph.issues.flatMap(issue => issue.paths || []));
    const state = {
      selectedId: "",
      query: "",
      provider: "",
      kind: "",
      edgeType: "",
      viewBox: null,
      layout: new Map(),
    };
    const search = document.getElementById('search');
    const provider = document.getElementById('provider');
    const kind = document.getElementById('kind');
    const edgeType = document.getElementById('edgeType');
    const nodeList = document.getElementById('nodeList');
    const svg = document.getElementById('graphSvg');
    const detailTitle = document.getElementById('detailTitle');
    const detailSubtitle = document.getElementById('detailSubtitle');
    const detail = document.getElementById('detail');
    const issues = document.getElementById('issues');
    const edgeTypes = [...new Set(edges.map(edge => edge.type))].sort();
    document.getElementById('metrics').innerHTML = [
      metric(graph.summary.nodeCount, 'nodes'),
      metric(graph.summary.edgeCount, 'edges'),
      metric(graph.summary.issueCount, 'issues'),
      metric(graph.contentHash, 'hash')
    ].join('');
    for (const value of [...new Set(nodes.flatMap(node => node.providerNames || [node.providerName]))].sort()) {
      const option = document.createElement('option');
      option.value = value;
      option.textContent = value;
      provider.append(option);
    }
    for (const value of [...new Set(nodes.map(node => node.kind))].sort()) {
      const option = document.createElement('option');
      option.value = value;
      option.textContent = value;
      kind.append(option);
    }
    for (const value of edgeTypes) {
      const option = document.createElement('option');
      option.value = value;
      option.textContent = value;
      edgeType.append(option);
    }
    function metric(value, label) {
      return '<div class="metric"><strong>' + html(value) + '</strong><span>' + html(label) + '</span></div>';
    }
    function html(value) {
      return String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
    }
    function textFor(node) {
      return [node.name, node.providerName, node.kind, node.path, node.description].join(' ').toLowerCase();
    }
    function providerMatch(node) {
      if (!state.provider) return true;
      return (node.providerNames || [node.providerName]).includes(state.provider);
    }
    function matchesNode(node) {
      if (state.kind && node.kind !== state.kind) return false;
      if (!providerMatch(node)) return false;
      if (state.query && !textFor(node).includes(state.query)) return false;
      return true;
    }
    function edgeAllowed(edge) {
      return !state.edgeType || edge.type === state.edgeType;
    }
    function relatedToSelection(edge) {
      return !state.selectedId || edge.source === state.selectedId || edge.target === state.selectedId;
    }
    function wrapText(value, max) {
      const words = String(value || '').split(/\\s+/);
      const lines = [];
      let line = '';
      for (const word of words) {
        const next = line ? line + ' ' + word : word;
        if (next.length > max && line) {
          lines.push(line);
          line = word;
        } else {
          line = next;
        }
      }
      if (line) lines.push(line);
      return lines.length ? lines.slice(0, 2) : [''];
    }
    function layoutGraph() {
      const rank = new Map(nodes.map(node => [node.id, 0]));
      const strongEdges = edges.filter(edge => edge.type !== 'references');
      for (let pass = 0; pass < nodes.length; pass += 1) {
        let changed = false;
        for (const edge of strongEdges) {
          if (!rank.has(edge.source) || !rank.has(edge.target)) continue;
          const next = Math.min(9, (rank.get(edge.source) || 0) + 1);
          if (next > (rank.get(edge.target) || 0)) {
            rank.set(edge.target, next);
            changed = true;
          }
        }
        if (!changed) break;
      }
      const connected = new Set(strongEdges.flatMap(edge => [edge.source, edge.target]));
      for (const node of nodes) {
        if (!connected.has(node.id)) rank.set(node.id, Math.max(rank.get(node.id) || 0, 0));
      }
      const groups = new Map();
      for (const node of nodes) {
        const key = rank.get(node.id) || 0;
        const list = groups.get(key) || [];
        list.push(node);
        groups.set(key, list);
      }
      const layout = new Map();
      const columnWidth = 270;
      const rowHeight = 100;
      const nodeWidth = 220;
      const nodeHeight = 72;
      let maxX = 0;
      let maxY = 0;
      for (const [column, list] of [...groups.entries()].sort((a, b) => a[0] - b[0])) {
        list.sort((a, b) => (a.popularityRank - b.popularityRank) || a.providerName.localeCompare(b.providerName) || a.name.localeCompare(b.name));
        list.forEach((node, index) => {
          const x = 42 + column * columnWidth;
          const y = 42 + index * rowHeight;
          layout.set(node.id, { x, y, width: nodeWidth, height: nodeHeight });
          maxX = Math.max(maxX, x + nodeWidth);
          maxY = Math.max(maxY, y + nodeHeight);
        });
      }
      state.layout = layout;
      state.bounds = { x: 0, y: 0, width: maxX + 70, height: maxY + 70 };
      if (!state.viewBox) fitAll();
    }
    function setViewBox(box) {
      state.viewBox = box;
      svg.setAttribute('viewBox', [box.x, box.y, box.width, box.height].join(' '));
    }
    function fitAll() {
      const bounds = state.bounds || { x: 0, y: 0, width: 1200, height: 800 };
      setViewBox({ x: bounds.x, y: bounds.y, width: Math.max(640, bounds.width), height: Math.max(440, bounds.height) });
    }
    function zoom(factor) {
      const box = state.viewBox || state.bounds;
      const cx = box.x + box.width / 2;
      const cy = box.y + box.height / 2;
      const width = Math.max(260, box.width * factor);
      const height = Math.max(220, box.height * factor);
      setViewBox({ x: cx - width / 2, y: cy - height / 2, width, height });
    }
    function centerOnNode(id) {
      const item = state.layout.get(id);
      if (!item) return;
      const box = state.viewBox || state.bounds;
      const width = Math.min(box.width, 920);
      const height = Math.min(box.height, 620);
      setViewBox({
        x: item.x + item.width / 2 - width / 2,
        y: item.y + item.height / 2 - height / 2,
        width,
        height,
      });
    }
    function renderList() {
      nodeList.textContent = '';
      const visible = nodes.filter(matchesNode);
      if (!visible.length) {
        nodeList.innerHTML = '<div class="empty">No skills match these filters.</div>';
        return;
      }
      for (const node of visible) {
        const button = document.createElement('button');
        button.type = 'button';
        button.className = 'node-row' + (state.selectedId === node.id ? ' active' : '');
        button.innerHTML = '<span class="row-title">' + html(node.name) + '</span><span class="row-meta">' + html(node.providerName) + ' | ' + html(node.kind) + '</span><br><span class="path">' + html(node.path) + '</span>';
        button.onclick = () => selectNode(node.id);
        nodeList.append(button);
      }
    }
    function createSvg(tag, attrs = {}) {
      const el = document.createElementNS('http://www.w3.org/2000/svg', tag);
      for (const [key, value] of Object.entries(attrs)) el.setAttribute(key, value);
      return el;
    }
    function renderGraph() {
      svg.textContent = '';
      const defs = createSvg('defs');
      defs.innerHTML = '<filter id="cardShadow" x="-10%" y="-20%" width="130%" height="150%"><feDropShadow dx="0" dy="5" stdDeviation="5" flood-color="#111827" flood-opacity=".10"/></filter><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#667085"/></marker>';
      svg.append(defs);
      const edgeLayer = createSvg('g');
      const nodeLayer = createSvg('g');
      svg.append(edgeLayer, nodeLayer);
      for (const edge of edges.filter(edgeAllowed)) {
        const source = state.layout.get(edge.source);
        const target = state.layout.get(edge.target);
        if (!source || !target) continue;
        const sourceNode = byId.get(edge.source);
        const targetNode = byId.get(edge.target);
        const visible = matchesNode(sourceNode) && matchesNode(targetNode);
        const selected = relatedToSelection(edge);
        const startX = source.x + source.width;
        const startY = source.y + source.height / 2;
        const endX = target.x;
        const endY = target.y + target.height / 2;
        const curve = Math.max(80, Math.abs(endX - startX) * .46);
        const path = createSvg('path', {
          d: 'M ' + startX + ' ' + startY + ' C ' + (startX + curve) + ' ' + startY + ', ' + (endX - curve) + ' ' + endY + ', ' + endX + ' ' + endY,
          class: 'edge-path ' + edge.type + ((!visible || !selected) ? ' dim' : ''),
          'marker-end': 'url(#arrow)',
        });
        edgeLayer.append(path);
        if (edge.type !== 'references' && visible) {
          const label = createSvg('text', {
            x: (startX + endX) / 2,
            y: (startY + endY) / 2 - 7,
            class: 'edge-label',
            'text-anchor': 'middle',
          });
          label.textContent = edge.label;
          edgeLayer.append(label);
        }
      }
      for (const node of nodes) {
        const item = state.layout.get(node.id);
        if (!item) continue;
        const visible = matchesNode(node);
        const related = !state.selectedId || state.selectedId === node.id || edges.some(edge => relatedToSelection(edge) && (edge.source === node.id || edge.target === node.id));
        const group = createSvg('g', {
          class: 'node-g ' + node.kind + (state.selectedId === node.id ? ' selected' : '') + (issuePaths.has(node.path) ? ' issue' : '') + ((!visible || !related) ? ' dim' : ''),
          transform: 'translate(' + item.x + ' ' + item.y + ')',
          tabindex: visible ? '0' : '-1',
          role: 'button',
        });
        group.addEventListener('click', () => selectNode(node.id));
        group.addEventListener('keydown', event => {
          if (event.key === 'Enter' || event.key === ' ') selectNode(node.id);
        });
        group.append(createSvg('rect', { class: 'node-rect', width: item.width, height: item.height }));
        const title = createSvg('text', { class: 'node-title', x: 12, y: 20 });
        wrapText(node.name, 25).forEach((line, index) => {
          const tspan = createSvg('tspan', { x: 12, dy: index ? 15 : 0 });
          tspan.textContent = line;
          title.append(tspan);
        });
        const subtitle = createSvg('text', { class: 'node-subtitle', x: 12, y: 52 });
        subtitle.textContent = node.providerName.length > 34 ? node.providerName.slice(0, 31) + '...' : node.providerName;
        const kindLabel = createSvg('text', { class: 'node-kind', x: 12, y: 66 });
        kindLabel.textContent = node.kind;
        group.append(title, subtitle, kindLabel);
        nodeLayer.append(group);
      }
    }
    function renderDetail() {
      const node = byId.get(state.selectedId);
      if (!node) {
        detailTitle.textContent = 'Select a skill';
        detailSubtitle.textContent = 'Click a node or list item to inspect dependencies.';
        detail.innerHTML = '<div class="empty">The map contains ' + html(nodes.length) + ' nodes across ' + html(graph.providers.length) + ' provider presets.</div>';
        return;
      }
      detailTitle.textContent = node.name;
      detailSubtitle.textContent = node.path;
      const related = edges.filter(edge => edge.source === node.id || edge.target === node.id);
      const nodeIssues = graph.issues.filter(issue => (issue.paths || []).includes(node.path));
      detail.innerHTML =
        '<div class="badge-row">' +
          '<span class="badge">' + html(node.kind) + '</span>' +
          '<span class="badge">' + html(node.providerName) + '</span>' +
          (nodeIssues.length ? '<span class="badge err">' + html(nodeIssues.length) + ' issue</span>' : '') +
        '</div>' +
        '<div class="detail-card"><h3>Description</h3><p>' + html(node.description || 'No description detected.') + '</p><p class="path">' + html(node.path) + '</p></div>' +
        '<h3>Edges</h3>' +
        (related.length ? related.map(edge => {
          const source = byId.get(edge.source)?.name || edge.source;
          const target = byId.get(edge.target)?.name || edge.target;
          return '<div class="edge-item ' + html(edge.type) + '"><strong>' + html(edge.type) + '</strong><br>' + html(source) + ' -> ' + html(target) + '<p class="path">' + html(edge.evidence || '') + '</p></div>';
        }).join('') : '<div class="empty">No inferred edges for this node.</div>');
    }
    function renderIssues() {
      issues.innerHTML = graph.issues.length
        ? graph.issues.map(issue => '<div class="issue ' + html(issue.severity) + '"><strong>' + html(issue.severity) + ' | ' + html(issue.type) + '</strong><br>' + html(issue.message) + '<p class="path">' + html((issue.paths || []).join(', ')) + '</p></div>').join('')
        : '<div class="empty">No issues detected.</div>';
    }
    function render() {
      renderList();
      renderGraph();
      renderDetail();
      renderIssues();
    }
    function selectNode(id) {
      state.selectedId = state.selectedId === id ? "" : id;
      render();
      if (state.selectedId) centerOnNode(state.selectedId);
    }
    function resetFilters() {
      state.query = "";
      state.provider = "";
      state.kind = "";
      state.edgeType = "";
      state.selectedId = "";
      search.value = "";
      provider.value = "";
      kind.value = "";
      edgeType.value = "";
      render();
      fitAll();
    }
    function syncFilters() {
      state.query = search.value.trim().toLowerCase();
      state.provider = provider.value;
      state.kind = kind.value;
      state.edgeType = edgeType.value;
      render();
    }
    let dragStart = null;
    svg.addEventListener('pointerdown', event => {
      dragStart = { x: event.clientX, y: event.clientY, box: { ...state.viewBox } };
      svg.classList.add('dragging');
      svg.setPointerCapture(event.pointerId);
    });
    svg.addEventListener('pointermove', event => {
      if (!dragStart) return;
      const rect = svg.getBoundingClientRect();
      const dx = (event.clientX - dragStart.x) * dragStart.box.width / rect.width;
      const dy = (event.clientY - dragStart.y) * dragStart.box.height / rect.height;
      setViewBox({ ...dragStart.box, x: dragStart.box.x - dx, y: dragStart.box.y - dy });
    });
    svg.addEventListener('pointerup', event => {
      dragStart = null;
      svg.classList.remove('dragging');
      svg.releasePointerCapture(event.pointerId);
    });
    svg.addEventListener('wheel', event => {
      event.preventDefault();
      zoom(event.deltaY > 0 ? 1.12 : .88);
    }, { passive: false });
    search.addEventListener('input', syncFilters);
    provider.addEventListener('change', syncFilters);
    kind.addEventListener('change', syncFilters);
    edgeType.addEventListener('change', syncFilters);
    document.getElementById('fit').addEventListener('click', fitAll);
    document.getElementById('zoomIn').addEventListener('click', () => zoom(.82));
    document.getElementById('zoomOut').addEventListener('click', () => zoom(1.18));
    document.getElementById('reset').addEventListener('click', resetFilters);
    layoutGraph();
    render();
  </script>
</body>
</html>
`;
}

export function writeOutputs(graph, outDir) {
  mkdirSync(outDir, { recursive: true });
  const files = {
    'skillgraph.json': jsonStable(graph),
    'SKILLGRAPH.md': generateMarkdown(graph),
    'skillgraph.html': generateHtml(graph),
  };
  for (const [name, content] of Object.entries(files)) {
    writeFileSync(join(outDir, name), content);
  }
  return files;
}

export function checkOutputs(graph, outDir) {
  const expected = {
    'skillgraph.json': jsonStable(graph),
    'SKILLGRAPH.md': generateMarkdown(graph),
    'skillgraph.html': generateHtml(graph),
  };
  const stale = [];
  for (const [name, content] of Object.entries(expected)) {
    const path = join(outDir, name);
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) stale.push(name);
  }
  return stale;
}

export function scanForbiddenTerms(rootDir, terms, exclude = DEFAULT_CONFIG.exclude) {
  const hits = [];
  function walk(currentAbs) {
    const repoPath = normalizePath(relative(rootDir, currentAbs));
    if (repoPath && isExcluded(repoPath, exclude)) return;
    const stat = statSync(currentAbs);
    if (stat.isDirectory()) {
      for (const entry of readdirSync(currentAbs)) walk(join(currentAbs, entry));
      return;
    }
    if (stat.size > 1024 * 1024) return;
    const text = readFileSync(currentAbs, 'utf8');
    const lines = text.split('\n');
    lines.forEach((line, index) => {
      for (const term of terms.filter(Boolean)) {
        if (line.toLowerCase().includes(term.toLowerCase())) {
          hits.push({ path: repoPath, line: index + 1, term });
        }
      }
    });
  }
  walk(rootDir);
  return hits;
}

function parseArgs(argv) {
  const args = { command: argv[2] || 'generate', roots: [] };
  for (let index = 3; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--config') args.configPath = argv[++index];
    else if (arg.startsWith('--config=')) args.configPath = arg.split('=')[1];
    else if (arg === '--root') args.rootDir = argv[++index];
    else if (arg.startsWith('--root=')) args.rootDir = arg.split('=')[1];
    else if (arg === '--out-dir') args.outDir = argv[++index];
    else if (arg.startsWith('--out-dir=')) args.outDir = arg.split('=')[1];
    else if (arg === '--skill-root') args.roots.push(argv[++index]);
    else if (arg.startsWith('--skill-root=')) args.roots.push(arg.split('=')[1]);
    else if (arg === '--terms-file') args.termsFile = argv[++index];
    else if (arg.startsWith('--terms-file=')) args.termsFile = arg.split('=')[1];
  }
  return args;
}

function printUsage() {
  console.log(`Skillgraph

Usage:
  skillgraph generate [--config skillgraph.config.json] [--root .]
  skillgraph check [--config skillgraph.config.json] [--root .]
  skillgraph audit [--config skillgraph.config.json] [--root .]
  skillgraph privacy-scan --terms-file docs/private-leak-terms.txt
`);
}

export async function runCli(argv = process.argv) {
  const args = parseArgs(argv);
  if (args.command === 'help' || args.command === '--help' || args.command === '-h') {
    printUsage();
    return;
  }
  if (args.command === 'privacy-scan') {
    const rootDir = resolve(args.rootDir || process.cwd());
    if (!args.termsFile) throw new Error('privacy-scan requires --terms-file');
    const terms = readFileSync(resolve(rootDir, args.termsFile), 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#'));
    const hits = scanForbiddenTerms(rootDir, terms, [...DEFAULT_CONFIG.exclude, normalizePath(args.termsFile)]);
    if (hits.length) {
      for (const hit of hits) console.error(`${hit.path}:${hit.line} contains forbidden term "${hit.term}"`);
      process.exit(1);
    }
    console.log(`Privacy scan passed: ${terms.length} terms`);
    return;
  }

  const config = loadConfig(args);
  const graph = buildSkillGraph({ config });
  if (args.command === 'generate') {
    writeOutputs(graph, config.outDirAbs);
    const outDir = normalizePath(relative(config.rootDir, config.outDirAbs));
    console.log(`Wrote skillgraph artifacts: ${outDir}`);
    console.log(`Open UI: ${normalizePath(join(outDir, 'skillgraph.html'))}`);
    console.log(`Nodes: ${graph.summary.nodeCount} | Edges: ${graph.summary.edgeCount} | Issues: ${graph.summary.issueCount}`);
    return;
  }
  if (args.command === 'check') {
    const stale = checkOutputs(graph, config.outDirAbs);
    if (stale.length) {
      console.error(`Skillgraph artifacts are stale: ${stale.join(', ')}`);
      console.error('Run: skillgraph generate');
      process.exit(1);
    }
    console.log(`Skillgraph artifacts are current: ${graph.summary.nodeCount} nodes, ${graph.summary.edgeCount} edges`);
    return;
  }
  if (args.command === 'audit') {
    console.log(JSON.stringify(graph.summary, null, 2));
    for (const issue of graph.issues) {
      const line = `${issue.severity.toUpperCase()} ${issue.type}: ${issue.message}`;
      if (issue.severity === 'error') console.error(line);
      else console.log(line);
    }
    if (graph.issues.some((issue) => issue.severity === 'error')) process.exit(1);
    return;
  }
  printUsage();
  process.exit(1);
}

export { DEFAULT_CONFIG, PROJECT_ROOT };
